version: "3.8"

services:
  app:
    image: islomw/wms-service:latest
    container_name: spring_app
    restart: always
    expose:
      - "8080"
    networks:
      - mynet
    depends_on:
      - db

  nginx:
    build: ./nginx
    container_name: nginx
    depends_on:
      - app
    networks:
      - mynet
    ports:
      - "80:80"
      - "443:443"

volumes:
  postgres_data:

networks:
  mynet:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1400