version: "3.8"

services:
  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: tawkenskiy
      POSTGRES_DB: wms-service
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mynet

  app:
    image: islomw/wms-service:latest
    container_name: spring_app
    restart: always
    expose:
      - "8080"
    networks:
      - mynet
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/wms-service
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: tawkenskiy

  nginx:
    build: ./nginx
    container_name: nginx
    depends_on:
      - app
    networks:
      - mynet
    ports:
      - "80:80"
      - "443:443"

volumes:
  postgres_data:

networks:
  mynet:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1400