spring:
  datasource:
    url: jdbc:postgresql://db:5432/wms-service
    username: postgres
    password: tawkenskiy
    driver-class-name: org.postgresql.Driver

  mail:
    host: smtp.gmail.com
    port: 587
    username: asqarovdanater@gmail.com
    password: kpdz vbti hkyc iawb
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none   # ??? dev ?????????, ??? prod ? validate
    show-sql: true
    properties:
      hibernate:
        default_schema: public
        format_sql: true

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    enabled: true
    default-schema: public

  sql:
    init:
      mode: never
