### Crate user
POST http://islom.online/api/v1/users
Content-Type: application/json

{
  "name": "Test",
  "clientCode": "test",
  "telegramId": 2132352,
  "email": "islom@gmail.com",
  "phone": "+998946292882"
}

### Register
POST http://localhost:8080/api/v1/auth/register
Content-Type: application/json

{
  "username":"islom",
  "email":"tawkenskiy000@gmail.com",
  "password":"asdffdsa",
  "phoneNumber": "901896996"
}
