name: CI/CD Deploy

on:
  push:
    branches: [ "master" ]

jobs:
  deploy:
    # МЕНЯЕМ ОБЛАКО GITHUB НА ТВОЙ СЕРВЕР
    runs-on: self-hosted

    steps:
      # 1. GitHub Runner скачивает код напрямую в свою папку на сервере
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Выполняем команды Docker напрямую (SSH больше не нужен)
      - name: Deploy on server
        run: |
          docker stop spring_app || true
          docker rm spring_app || true
          docker-compose pull app nginx
          docker-compose up -d --no-deps --build app nginx